In [1]:
#LUBNA JAHAN LIPA
#0432310005101088

import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
A=np.array([[8+2, 8+1], [2*8, 8+2]])
print(A)

[[10  9]
 [16 10]]


In [8]:
# Finding shape
shape=np.shape(A)
print(shape)

# Finding Determinant
det_a=np.linalg.det(A)
print(det_a)

# Finding Rank
rank=np.linalg.matrix_rank(A)
print(rank)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

# Finding Inverse
if det_a!=0:
  inv_matrix=np.linalg.inv(A)
else:
  inv_matrix="Impossible"

print(inv_matrix)

(2, 2)
-43.99999999999999
2
[22. -2.]
[[ 0.6 -0.6]
 [ 0.8  0.8]]
[[-0.22727273  0.20454545]
 [ 0.36363636 -0.22727273]]


In [4]:
# New value is now at (1,2) position
B=np.array([[8+2, 8+1+1], [2*8, 8+2]])
print(B)

[[10 10]
 [16 10]]


In [9]:
# Finding shape
shape=np.shape(B)
print(shape)

# Finding Determinant
det_b=np.linalg.det(B)
print(det_b)

# Finding Rank
rank=np.linalg.matrix_rank(B)
print(rank)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(B)
print(eigenvalues)
print(eigenvectors)

# Finding Inverse
if det_b!=0:
  inv_matrix=np.linalg.inv(B)
else:
  inv_matrix="Impossible"

print(inv_matrix)

(2, 2)
-59.999999999999986
2
[22.64911064 -2.64911064]
[[ 0.62017367 -0.62017367]
 [ 0.78446454  0.78446454]]
[[-0.16666667  0.16666667]
 [ 0.26666667 -0.16666667]]


1.
The determinant decreased from −43 to −59.
It changed because the determinant depends directly on the values of the matrix elements. When I increased one element (top-right) by 1, it increased the product add, which changed the final subtraction result. Even a small change in one element can significantly affect the determinant.

2.
No, the rank did not change. Both matrices still have non-zero determinants. For a 2×2 matrix, if the determinant is not zero, the rank is 2. Rank only changes if a row becomes linearly dependent on another. Since det ≠ 0, rank stays full.

3.
The eigenvalues changed slightly. Eigenvalues depend on both the trace (sum of diagonal elements) and the determinant. Since we increased one diagonal element, the trace increased, and the determinant also changed. Because eigenvalues are calculated from these values, they adjusted accordingly. So, Changing a diagonal entry directly shifts the eigenvalue sum by the same amount.

4.
Matrix B is easier to invert because:
A matrix with a larger absolute determinant is farther from singular. Determinant is |-59|>|-43|, so B is more numerically stable and less sensitive to rounding errors. Therefore, B is easier (more stable) to invert than A.